<a href="https://colab.research.google.com/github/G-Shino/colab_tutorial/blob/master/Kitchen.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 属性の一覧

In [0]:
a = "hoge"

In [0]:
type(a)

str

In [0]:
dir(a)

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getnewargs__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmod__',
 '__rmul__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'capitalize',
 'casefold',
 'center',
 'count',
 'encode',
 'endswith',
 'expandtabs',
 'find',
 'format',
 'format_map',
 'index',
 'isalnum',
 'isalpha',
 'isdecimal',
 'isdigit',
 'isidentifier',
 'islower',
 'isnumeric',
 'isprintable',
 'isspace',
 'istitle',
 'isupper',
 'join',
 'ljust',
 'lower',
 'lstrip',
 'maketrans',
 'partition',
 'replace',
 'rfind',
 'rindex',
 'rjust',
 'rpartition',
 'rsplit',
 'rstrip',
 'split',
 'splitlines',
 'startswith',
 'strip',
 'swapcase',
 'title',
 'translate',
 'upper',
 'zfill']

In [0]:
b = [1, 2, 3]

In [0]:
type(b)

list

In [0]:
dir(b)

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

# 解説用の属性

In [0]:
a.__doc__

"str(object='') -> str\nstr(bytes_or_buffer[, encoding[, errors]]) -> str\n\nCreate a new string object from the given object. If encoding or\nerrors is specified, then the object must expose a data buffer\nthat will be decoded using the given encoding and error handler.\nOtherwise, returns the result of object.__str__() (if defined)\nor repr(object).\nencoding defaults to sys.getdefaultencoding().\nerrors defaults to 'strict'."

In [0]:
b.__doc__

"list() -> new empty list\nlist(iterable) -> new list initialized from iterable's items"

# クラスにおけるプロパティの設定

In [0]:
'''Dog クラス'''
class Dog():
     
    '''初期化メソッド'''
    def __init__(self):
        self.__name = "John" #非公開変数 __name
        
    '''クラスブロック内で非公開変数を使ったメソッドを作ります。'''
    def dogname(self):
        return self.__name
     
    '''nameプロパティのgetter'''
    @property
    def name(self): #プロパティ名は name です。
        return self.__name #__nameの値を返す。
     
    '''nameプロパティのsetter'''
    @name.setter
    def name(self, value): #getter と同じプロパティ名にします。
        self.__name = value #__nameの値を変更する

In [0]:
dog = Dog()

In [0]:
type(dog)

__main__.Dog

In [0]:
dog.name

'John'

In [0]:
dog.name = "sary"

In [0]:
dog.name

'sary'

In [0]:
'''Dog クラス'''
class Cat():
     
    '''初期化メソッド'''
    def __init__(self):
        self.__name = "tama" #非公開変数 __name
        
    '''クラスブロック内で非公開変数を使ったメソッドを作ります。'''
    def catname(self):
        return self.__name

In [0]:
cat = Cat()

In [0]:
cat.__name

AttributeError: ignored

In [0]:
cat.catname()

'tama'

In [0]:
class Spam():
  pass

In [0]:
spam = Spam()
type(spam)

__main__.Spam

In [0]:
type(int)

type

In [0]:
type(type)

type

# pythonのidentityについて

In [0]:
l1 = m1 = n1 = ['y', 'a', 'r', 'u', 'o']

l1.pop()

id(l1) == id(m1) == id(n1)

True

In [0]:
l2 = ['y', 'a', 'r', 'u', 'o']
m2 = ['y', 'a', 'r', 'u', 'o']
n2 = ['y', 'a', 'r', 'u', 'o']

id(l2) == id(m2) == id(n2)

False

In [0]:
a = 3
id(a)

10910464

In [0]:
b = 3
id(b)

10910464

In [0]:
a == b

True

In [0]:
id(a) == id(b)

True

In [0]:
a = [1, 2, 3]
id(a)

140175500320840

In [0]:
b = [1, 2, 3]
id(b)

140175500321096

In [0]:
a == b

True

In [0]:
id(a) == id(b)

False

In [0]:
for i, v in enumerate(a):
  print("a[",a[i], "]:", id(a[i]))
  print("v=",v, ":", id(v))

a[ 1 ]: 10910400
v= 1 : 10910400
a[ 2 ]: 10910432
v= 2 : 10910432
a[ 3 ]: 10910464
v= 3 : 10910464


In [0]:
class Person():
    def __init__(self, name):
        self.name = name

person = Person('やる夫')
print(person.name)
print(id(person.name))


#
# 変数への代入
#
def change_name(name):
    # 変数 = オブジェクト
    name = '岩倉玲音'
    print(name)
    print(id(name))


change_name(person.name)
print(person.name)  # 実行結果 1
print(id(person.name))

print("*" * 100)
#
# 属性への代入
#
def change_person_name(person):
    # オブジェクト.属性 = オブジェクト
    person.name = 'サーバルちゃん'
    print(person.name)
    print(id(person.name))


change_person_name(person)
print(person.name)  # 実行結果 2
print(id(person.name))

やる夫
140175500347024
岩倉玲音
140175500214320
やる夫
140175500347024
****************************************************************************************************
サーバルちゃん
140175500233432
サーバルちゃん
140175500233432


In [0]:
def change_name(name):
    # 変数 = オブジェクト
    name = '岩倉玲音'
    print(name)
    print(id(name))
    return name

b = "spam"
print(b, id(b))
change_name(b)
print(b, id(b))
b = change_name(b)
print(b, id(b))

spam 140175500317056
岩倉玲音
140175500215360
spam 140175500317056
岩倉玲音
140175500215360
岩倉玲音 140175500215360


In [0]:
a=[1,2,3]
b=a
a_0=a[0]
print(a[0])
print(id(a)==id(b))
print(id(a[0])==id(a_0)) 
print("*" * 100)
b[0]=5
print(a[0])
print(id(a)==id(b))
print(id(a[0])==id(a_0))
print("*" * 100)
b=[4,5,6]
print(id(a)==id(b))


1
True
True
****************************************************************************************************
5
True
False
****************************************************************************************************
False


## 浅いコピー

In [0]:
from copy import copy

lst0 = [None for _ in range (3)]
lst1 = lst0
lst2 = copy(lst0)  # lst0.copy() と完全に同じことをしてます。

lst0[0] = 0
lst0[1] = 1
lst0[2] = 2

print(lst0)
print(lst1)
print(lst2)

[0, 1, 2]
[0, 1, 2]
[None, None, None]


In [0]:
from copy import copy

lst0 = [[None for _ in range (3)] for _ in range(3)]
lst1 = lst0
lst2 = copy(lst0)

lst0[0][0] = 0
lst0[0][1] = 1
lst0[0][2] = 2

print(lst0)
print(lst1)
print(lst2)

[[0, 1, 2], [None, None, None], [None, None, None]]
[[0, 1, 2], [None, None, None], [None, None, None]]
[[0, 1, 2], [None, None, None], [None, None, None]]


## 深いコピー

In [0]:
from copy import deepcopy

lst0 = [[None for _ in range (3)] for _ in range(3)]
lst1 = lst0
lst2 = deepcopy(lst0)

lst0[0][0] = 0
lst0[0][1] = 1
lst0[0][2] = 2

print(lst0)
print(lst1)
print(lst2)

[[0, 1, 2], [None, None, None], [None, None, None]]
[[0, 1, 2], [None, None, None], [None, None, None]]
[[None, None, None], [None, None, None], [None, None, None]]


# 複数の引数を持つlambda関数

In [0]:
ary1 = [1, 2, 3]
ary2 = [5, 6, 7]
ret = map(lambda val1, val2: val1 * val2, ary1, ary2)
print(list(ret))
print(sum(ret))

[5, 12, 21]
0


# pythonによるデータ分析入門の気になったところ

In [0]:
states = ["     Alabama ", "Georgia!", "georgia", "FlOrIda", "south   carolina##", "West virginia?"]

In [0]:
import re
#!,#,?を削除(""に置き換える)
def remove_puctuation(value):
  return re.sub("[!#?]", "", value)

#stripで空白削除 titleで単語の先頭を大文字に
#関数を引数にしている
clean_ops = [str.strip, remove_puctuation, str.title]

def clean_strings(strings, ops):
  result = list()
  for value in strings:
    for function in ops:
      value = function(value)
    result.append(value)
  return result

In [0]:
clean_strings(states, clean_ops)

['Alabama',
 'Georgia',
 'Georgia',
 'Florida',
 'South   Carolina',
 'West Virginia']

In [0]:
words = ["apple", "bat", "bar", "atom", "book"]
by_letter = dict()
for word in words:
  letter = word[0]
  #第一引数に指定したキーが存在しない場合、新たな要素が追加される。
  #第一引数に指定したキーがすでに存在している場合は、第二引数にどんな値を指定しても元のオブジェクトのまま変更されない
  #また、このとき、第一引数に指定したキーに対応する値を返却する
  by_letter.setdefault(letter, []).append(word)
print(by_letter)

{'a': ['apple', 'atom'], 'b': ['bat', 'bar', 'book']}


In [0]:
pitches = [("1", "2"), ("3", "4"), ("5", "6")]
hoge, hoge2 = zip(*pitches)

In [0]:
hoge

('1', '3', '5')

In [0]:
hoge2

('2', '4', '6')

# numpy

- いろいろ雑多な感じ

## reshape

In [0]:
import numpy as np
a = np.arange(24)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [0]:
#reshapeは破壊的操作ではない
a.reshape((4, 6))

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [0]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [0]:
#コピーするときはメソッドを使う
a_reshape = a.reshape((4, 6)).copy()
print(a_reshape)
print(a_reshape.shape)
print(a_reshape.ndim)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
(4, 6)
2


In [0]:
#reshape(-1)で次元数を自動で決めてくれる
a_reshape.reshape(-1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

## 初期用の配列の生成

In [0]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)
print(type(a))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [0]:
a0 = np.zeros(3)
print(a0)
print("*" * 50)
a0 = np.zeros((2, 3))
print(a0)
print(a0.dtype)

[0. 0. 0.]
**************************************************
[[0. 0. 0.]
 [0. 0. 0.]]
float64


In [0]:
a1 = np.ones((2, 3))
print(a1)

[[1. 1. 1.]
 [1. 1. 1.]]


In [0]:
#任意の数で埋める
a_f = np.full(3, 100)
print(a_f)
a_f = np.full(3, np.pi)
print(a_f)

[100 100 100]
[3.14159265 3.14159265 3.14159265]


In [0]:
#同一形状で初期化する系統
a_int = np.arange(6).reshape((2, 3))
print(a_int)

a0 = np.zeros_like(a_int)
a1 = np.ones_like(a_int)
a2 = np.full_like(a_int, 100)
print("*" * 30)
print(a0)
print("*" * 30)
print(a1)
print("*" * 30)
print(a2)
print("*" * 30)

[[0 1 2]
 [3 4 5]]
******************************
[[0 0 0]
 [0 0 0]]
******************************
[[1 1 1]
 [1 1 1]]
******************************
[[100 100 100]
 [100 100 100]]
******************************


## 連番、等差数列の生成

In [0]:
#連番を生成したいとき
#np.arange(start, stop, step)は間隔主体
#np.linspace(start, stop, num)は要素数主体なイメージ

b = np.arange(20)
print(b)
b = np.arange(10, 3, -2, dtype="float32")
print(b)
b = np.linspace(0, 10, 3)
print(b)
b = np.linspace(10, 0, 4)
print(b)

#間隔の取得
b = np.linspace(0, 10, 3, retstep=True)
print(b[0])
print(b[1])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[10.  8.  6.  4.]
[ 0.  5. 10.]
[10.          6.66666667  3.33333333  0.        ]
[ 0.  5. 10.]
5.0


In [0]:
#逆順の取得
#[start:stop:step]
b = np.arange(10)[::-1]
print(b)
b = np.flip(np.arange(10))
print(b)

[9 8 7 6 5 4 3 2 1 0]
[9 8 7 6 5 4 3 2 1 0]


## 配列の結合

In [59]:
#基本的にはnp.concatenateとstackでおけ
#ただ二次元配列に対しては、vstackやhstackも便利

#concatenateは結合 
#stackは新たな軸を積み重ねるイメージ
import numpy as np
a1 = np.ones((3,), dtype="int64")
a2 = np.full((3,), 2)
a_con = np.concatenate([a1, a2], axis=0)
print("concatenate")
print(a_con)
print("*" * 10)

a1 = np.ones((2, 3), int)
a2 = np.full((2, 3), 2)
a_con = np.concatenate([a1, a2], axis=0)
print("concatenate")
print(a_con)
print("*" * 10)
a_con = np.concatenate([a1, a2], axis=1)
print(a_con)
print("*" * 10)

concatenate
[1 1 1 2 2 2]
**********
concatenate
[[1 1 1]
 [1 1 1]
 [2 2 2]
 [2 2 2]]
**********
[[1 1 1 2 2 2]
 [1 1 1 2 2 2]]
**********


In [60]:
a1 = np.ones((3,), dtype="int64")
a2 = np.full((3,), 2)
# print(a1)
# print("*" * 10)
# print(a2)
# print("*" * 10)

a_sta = np.stack([a1, a2], axis=0)
print("stack 1D")
print(a_sta)
print("*" * 10)
a_sta = np.stack([a1, a2], axis=1)
print(a_sta)
print("*" * 10)

print("stack 2D")
a1 = np.ones((3, 4), dtype="int64")
a2 = np.full((3, 4), 2)
a_sta = np.stack([a1, a2], axis=0)
print(a_sta)
print(a_sta.shape)
a_sta = np.stack([a1, a2], axis=1)
print(a_sta)
print(a_sta.shape)
a_sta = np.stack([a1, a2], axis=2)
print(a_sta)
print(a_sta.shape)

stack 1D
[[1 1 1]
 [2 2 2]]
**********
[[1 2]
 [1 2]
 [1 2]]
**********
stack 2D
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[2 2 2 2]
  [2 2 2 2]
  [2 2 2 2]]]
(2, 3, 4)
[[[1 1 1 1]
  [2 2 2 2]]

 [[1 1 1 1]
  [2 2 2 2]]

 [[1 1 1 1]
  [2 2 2 2]]]
(3, 2, 4)
[[[1 2]
  [1 2]
  [1 2]
  [1 2]]

 [[1 2]
  [1 2]
  [1 2]
  [1 2]]

 [[1 2]
  [1 2]
  [1 2]
  [1 2]]]
(3, 4, 2)


In [66]:
#np.blockは直感的　配置したとおりに結合される
a1 = np.ones((2, 3), dtype="int64")
a2 = np.full((2, 3), 2)
a_blo = np.block([a1, a2])
print(a_blo)
print("*****************")
a_blo = np.block([[a1, a2], [a2, a1]])
print(a_blo)
a3 = np.full(6, 3)
print("*****************************")
print(np.block([[a1, a2], [a3]]))

[[1 1 1 2 2 2]
 [1 1 1 2 2 2]]
*****************
[[1 1 1 2 2 2]
 [1 1 1 2 2 2]
 [2 2 2 1 1 1]
 [2 2 2 1 1 1]]
*****************************
[[1 1 1 2 2 2]
 [1 1 1 2 2 2]
 [3 3 3 3 3 3]]


In [71]:
#np.vstack()で縦に結合 
#二次元配列だとnp.concatenate(***, axis=0)と一緒
a1 = np.ones((2, 3), dtype="int64")
a2 = np.full((2, 3), 2)
a_vst = np.vstack([a1, a2])
print(a_vst)
print("++++++++++++++++++")
#一次元配列は二次元配列に拡張される。np.stack(*****, axis=0)と一緒
a1 = np.ones(3, dtype="int64")
a2 = np.full(3,2)
a_vst = np.vstack([a1, a2])
print(a_vst)
a1 = np.ones((2, 3), dtype="int64")
a2 = np.full(3, 2)
a_vst = np.vstack([a1, a2])
print("++++++++++++")
print(a_vst)

[[1 1 1]
 [1 1 1]
 [2 2 2]
 [2 2 2]]
++++++++++++++++++
[[1 1 1]
 [2 2 2]]
++++++++++++
[[1 1 1]
 [1 1 1]
 [2 2 2]]


In [76]:
#np.vstack()で縦に結合 
#二次元配列だとnp.concatenate(***, axis=1)と一緒
a1 = np.ones((2, 3), dtype="int64")
a2 = np.full((2, 3), 2)
a_hst = np.hstack([a1, a2])
print(a_hst)
print("++++++++++++++++++")
#一次元配列は、bnp.concatenate(*****, axis=0)と一緒
a1 = np.ones(3, dtype="int64")
a2 = np.full(3, 2)
a_hst = np.hstack([a1, a2])
print(a_hst)


[[1 1 1 2 2 2]
 [1 1 1 2 2 2]]
++++++++++++++++++
[1 1 1 2 2 2]


## 配列の分割

# pandas

In [0]:
# df_default = pd.read_csv('data/src/sample_header_index_dtype.csv', index_col=0)
# print(df_default)
# print(df_default.dtypes)
# print(df_default.applymap(type))

## pandas.DataFrame

In [82]:
import pandas as pd
import numpy as np
from IPython.display import display

df_simple = pd.DataFrame(np.arange(12).reshape(3, 4))
# print(df_simple)
print(type(df_simple))
display(df_simple)
print("index")
print(df_simple.index)
print(list(df_simple.index))
print(df_simple.columns)
print(list(df_simple.columns))

<class 'pandas.core.frame.DataFrame'>


0  1   2   3
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

index
RangeIndex(start=0, stop=3, step=1)
[0, 1, 2]
RangeIndex(start=0, stop=4, step=1)
[0, 1, 2, 3]


In [84]:
df = pd.DataFrame(np.arange(12).reshape(3, 4), 
                 columns=["col0", "col1", "col2", "col3"],
                 index=["row0", "row1", "row2"])
display(df)

col0  col1  col2  col3
row0     0     1     2     3
row1     4     5     6     7
row2     8     9    10    11

In [96]:
#列の選択
print(df.col1)
print(df["col1"])

#要素の選択 単独の場合はatの方が高速だったりする
print(df.loc["row1", "col1"])
print(df.loc[["row2", "row0"], ["col1", "col3"]])

row0    1
row1    5
row2    9
Name: col1, dtype: int64
row0    1
row1    5
row2    9
Name: col1, dtype: int64
5
      col1  col3
row2     9    11
row0     1     3


In [97]:
#要素の変更
df.loc[:] = np.arange(12).reshape(3, 4) * 100
display(df)

col0  col1  col2  col3
row0     0   100   200   300
row1   400   500   600   700
row2   800   900  1000  1100

In [100]:
#辞書形式でも作成できる 欠損値はNaN
display(pd.DataFrame([{'col_0': 0, 'col_1': 1},
                    {'col_0': 3, 'col_1': 4, 'col_2': 5},
                    {'col_0': 6, 'col_1': 7, 'col_2': 8}]))

col_0  col_1  col_2
0      0      1    NaN
1      3      4    5.0
2      6      7    8.0

# その他

In [0]:
int.__base__

object

In [0]:
bool.__base__

int

In [0]:
float.__base__

object

In [0]:
#intを継承しているイメージ
0 == False
1 == True
True + True

2

In [0]:
def create_counter():
    c = 0
    def count():
        nonlocal c  # １つ外側の変数 c を束縛する。
        print(locals())
        c = c + 1
        return c
    print(locals())
    return count
  
count = create_counter()
count()
count()
count()

{'count': <function create_counter.<locals>.count at 0x7fcd07ab8ae8>, 'c': 0}
{'c': 0}
{'c': 1}
{'c': 2}


3

In [0]:
type(count)

function

In [0]:
def func():
    x = 3
    def value(v):
        nonlocal x
        x = v
    def add(y):
        return y+x
    x = 5
    return value, add

v, f = func()
print(f(4)) # 9 = 5 + 4 
v(10) # x の値が 5 → 10 に更新される
print(f(4)) # 14 = 4 + 10

9
14


In [0]:
def func():
    x = 3
    print("func name space : ", locals())
    def add3(y):
        print("add3 name space : ", locals())
        return y+x
    return add3

f = func()
print(f(4)) # 7

func name space :  {'x': 3}
add3 name space :  {'y': 4, 'x': 3}
7
